import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const settingsPath = resolve(root, 'src/client-settings.js')
const mobilePath = resolve(root, 'vendor/dsh-web-mobile/client.js')
const outputPath = resolve(root, 'client.js')

function factoryBody(source, label) {
  const marker = 'factory: (require) => {'
  const start = source.indexOf(marker)
  if (start < 0) throw new Error(`${label}: DSH client factory marker not found`)
  const lastReturn = source.lastIndexOf('return module.exports')
  if (lastReturn < start) throw new Error(`${label}: final module export not found`)
  const end = source.indexOf('}', lastReturn)
  if (end < 0) throw new Error(`${label}: client factory closing brace not found`)
  return source.slice(start + marker.length, end).trim()
}

function adaptMobileSource(source) {
  const replacements = new Map([
    ['@dsh-external/dsh-mobile-nav', 'dsh-wechat-bridge/mobile-ui'],
    ['dsh-mobile-nav:', 'dsh-wechat-bridge/mobile-ui:'],
    ['background:rgba(0,0,0,.82)', 'background:var(--dsw-alias-bg-mask-photo)'],
    ['color:#fff', 'color:var(--dsw-static-neutral-00)'],
    ['var(--ds-ease-in-out, ease-in-out)', 'ease-in-out'],
    ['var(--ds-ease-out, ease-in-out)', 'ease-in-out'],
    ['var(--dsw-alias-bg-base, #ffffff)', 'var(--dsw-alias-bg-base)'],
    ['var(--dsw-alias-interactive-bg-hover, rgba(0, 0, 0, .06))', 'var(--dsw-alias-interactive-bg-hover)'],
    ['var(--aion-bg-base, #ffffff)', 'var(--dsw-alias-bg-base)'],
    ['0 -4px 28px rgba(0, 0, 0, .18)', '0 -4px 28px var(--dsw-alias-bg-mask-2)'],
    ['var(--aion-text-secondary, var(--dsw-alias-label-secondary, inherit))', 'var(--dsw-alias-label-secondary)'],
    ['var(--aion-bg-3, rgba(0, 0, 0, .22))', 'var(--dsw-alias-bg-module-platform)'],
    ['var(--aion-bg-active, rgba(0, 0, 0, .28))', 'var(--dsw-alias-interactive-bg-hover-solid)'],
    ['var(--dsw-alias-state-business-primary, #4f6ef7)', 'var(--dsw-alias-state-business-primary)'],
    ['var(--dsw-alias-border-l2, rgba(0, 0, 0, .22))', 'var(--dsw-alias-border-l2)'],
    ['var(--dsw-alias-border-l1, rgba(0, 0, 0, .12))', 'var(--dsw-alias-border-l1)'],
    ['var(--dsw-alias-border-l1, rgba(0, 0, 0, .28))', 'var(--dsw-alias-border-l1)'],
    ['var(--dsw-alias-label-tertiary, rgba(0, 0, 0, .3))', 'var(--dsw-alias-label-tertiary)'],
    ['var(--dsw-alias-label-dimmed, rgba(0, 0, 0, .35))', 'var(--dsw-alias-label-dimmed)'],
    ['var(--dsw-alias-button-floating-fill, #ffffff)', 'var(--dsw-alias-button-floating-fill)'],
    ['0 2px 12px rgba(0, 0, 0, .18)', '0 2px 12px var(--dsw-alias-bg-mask-2)'],
    ['var(--dsw-alias-button-floating-hover, rgba(0, 0, 0, .08))', 'var(--dsw-alias-button-floating-hover)'],
    ['background: rgba(0, 0, 0, .45)', 'background: var(--dsw-alias-bg-mask-3)'],
  ])
  let adapted = source
  for (const [from, to] of replacements) adapted = adapted.replaceAll(from, to)
  const forbidden = [
    ['non-DSH Aion UI variables', /--aion-/u],
    ['non-DSW motion variables', /--ds-ease/u],
    ['raw hexadecimal colours', /#[0-9a-f]{3,8}\b/iu],
    ['raw rgb colours', /rgba?\(/iu],
  ]
  for (const [label, pattern] of forbidden) {
    if (pattern.test(adapted)) throw new Error(`adapted mobile UI still contains ${label}`)
  }
  return adapted
}

const settingsSource = await readFile(settingsPath, 'utf8')
const mobileSource = adaptMobileSource(await readFile(mobilePath, 'utf8'))
const settingsBody = factoryBody(settingsSource, 'settings client')
const mobileBody = factoryBody(mobileSource, 'dsh-web-mobile client')

const output = `// Generated by scripts/build-client.mjs. Do not edit directly.\n` +
`// Mobile UI adapted from mexiaosqwq/dsh-web-mobile at a96035f (MIT).\n` +
`window.__ModuleLoader__.load({\n` +
`  id: 'dsh-wechat-bridge',\n` +
`  factory: (require) => {\n` +
`    const settingsPlugin = (() => {\n${settingsBody}\n    })()\n` +
`    const mobilePlugin = (() => {\n${mobileBody}\n    })()\n` +
`    const plugins = [settingsPlugin, mobilePlugin]\n` +
`    return {\n` +
`      inject: [...new Set(plugins.flatMap((plugin) => plugin.inject || []))],\n` +
`      apply(ctx) {\n` +
`        for (const plugin of plugins) plugin.apply(ctx)\n` +
`      },\n` +
`    }\n` +
`  },\n` +
`})\n`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, output)
console.log(`combined client bundle written: ${outputPath}`)
