import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const settingsPath = resolve(root, 'src/client-settings.js')
const outputPath = resolve(root, 'client.js')

function factoryBody(source, label) {
  const marker = 'factory: (require) => {'
  const start = source.indexOf(marker)
  if (start < 0) throw new Error(`${label}: DSH client factory marker not found`)
  const lastReturn = source.lastIndexOf('return module.exports')
  if (lastReturn < start) throw new Error(`${label}: final module export not found`)
  const end = source.indexOf('}', lastReturn)
  if (end < 0) throw new Error(`${label}: client factory closing brace not found`)
  return source.slice(start + marker.length, end).trim()
}

const settingsSource = await readFile(settingsPath, 'utf8')
const settingsBody = factoryBody(settingsSource, 'settings client')

const output = `// Generated by scripts/build-client.mjs. Do not edit directly.\n` +
`window.__ModuleLoader__.load({\n` +
`  id: 'dsh-wechat-bridge',\n` +
`  factory: (require) => {\n` +
`    const settingsPlugin = (() => {\n${settingsBody}\n    })()\n` +
`    const plugins = [settingsPlugin]\n` +
`    return {\n` +
`      inject: [...new Set(plugins.flatMap((plugin) => plugin.inject || []))],\n` +
`      apply(ctx) {\n` +
`        for (const plugin of plugins) plugin.apply(ctx)\n` +
`      },\n` +
`    }\n` +
`  },\n` +
`})\n`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, output)
console.log(`settings-only client bundle written: ${outputPath}`)
